### ISSUE TITLE
How to store AccessToken/RefreshToken/TokenType?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/go-uaa#1]
If my CLI captures the username/password from a user, and then use `uaa.NewWithPasswordCredentials(..)` to construct my `uaa.API`, how do I get the AccessToken/RefreshToken/TokenType from `uaa.API` so I can store it locally for later use (subsequent CLI commands) without needing to cache the username/password?

**Comment by drnic** [comment]
I've started a PR at #4 where `uaa.NewWithPasswordCredentials` returns a wrapper struct that holds `passwordcredentials.Config` to allow `.Tokens()` to be invoked and extracted.

**Comment by drnic** [comment]
The other reason for exporting the token is to use it to call non-UAA APIs https://github.com/starkandwayne/ultimate-guide-to-uaa-examples/blob/3d9294bbb477cba65e7cc6d6cdbe62caa916db08/golang/resource-server-cli/src/resource-server-cli/main.go#L96-L116

**Comment by joefitzgerald** [comment]
This is fixed in [v0.2.0](https://github.com/cloudfoundry-community/go-uaa/releases/tag/v0.2.0), which includes a `uaa.API.Token` function.

**Comment by drnic** [comment]
Thanks @joefitzgerald
