### ISSUE TITLE
issue with special character in client secret

### ISSUE THREAD

**Issue by strehle** [cloudfoundry-community/go-uaa#10]
go-uaa uses oauth2 from standard go and this encodes authorization header according to standard
RFC, see
https://github.com/golang/oauth2/blob/master/internal/token.go#L195

However UAA as backend server does not handle this encoding, see existing issue on
https://github.com/cloudfoundry/uaa/issues/778

I would like to have a direction for a fix, means, use non RFC complient encoding in go-uaa (uaa-cli) or fix UAA .
Problem now it, that uaa-cli (client) and uaa (server) are not working together if special characters in secret

e.g.
client_id: admin
client_secret: admin#secret

**Comment by joefitzgerald** [comment]
I think using standard / RFC compliant encoding is appropriate, so I'm going to close this issue.
